### ISSUE TITLE
Cannot consume REST API using Angular

### ISSUE THREAD

**Issue by chenry** [Google-IO-Extended-Grand-Rapids/conference_webapp#16]
- branch: feature/consume_conferences_api

Looking at this branch, I have a sample.js.  It is currently consuming the openweather api, without any problems.  There is a commented out block of code that specifies the REST API for our application, and it is not working.

Any thoughts as to why this is the case?

**Comment by will1771** [comment]
On the console it is showing:
`
No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:63342' is therefore not allowed access.
`

Since it doesn't do that for the weather api, I'm guessing we need to do something in conference-web to let the cross-domain requests through.  I was going to try to add this filter to the webapp:
https://spring.io/guides/gs/rest-service-cors/

However, it turns out I still don't know how to redeploy conference-web without blowing away the whole VM yet.

**Comment by chenry** [comment]
@will171 I think that you may have found the solution. We are working on getting develop fixed. 

Thank you

**Comment by chenry** [comment]
@will1771 if you want to give it a shot, if you created a hotfix from the master branch, that version of the code base should work, and I would get this pushed to production.

**Comment by will1771** [comment]
OK cool.

**Comment by will1771** [comment]
PR is in, I can't link it because it's a different repo.

**Comment by chenry** [comment]
I have merged the PR.  Thanks @will1771 

When we deploy this to production, we can then test this out.

**Comment by chenry** [comment]
We have tested this and it is now working.  Thanks again @will1771
